# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from interfaces import datetime_pb2 as interfaces_dot_datetime__pb2


class DateTimeStub(object):
    """The datetime service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTime = channel.unary_unary(
                '/datetime.DateTime/GetTime',
                request_serializer=interfaces_dot_datetime__pb2.TimeRequest.SerializeToString,
                response_deserializer=interfaces_dot_datetime__pb2.TimeReply.FromString,
                )
        self.GetDate = channel.unary_unary(
                '/datetime.DateTime/GetDate',
                request_serializer=interfaces_dot_datetime__pb2.DateRequest.SerializeToString,
                response_deserializer=interfaces_dot_datetime__pb2.DateReply.FromString,
                )


class DateTimeServicer(object):
    """The datetime service definition.
    """

    def GetTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DateTimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTime,
                    request_deserializer=interfaces_dot_datetime__pb2.TimeRequest.FromString,
                    response_serializer=interfaces_dot_datetime__pb2.TimeReply.SerializeToString,
            ),
            'GetDate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDate,
                    request_deserializer=interfaces_dot_datetime__pb2.DateRequest.FromString,
                    response_serializer=interfaces_dot_datetime__pb2.DateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datetime.DateTime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DateTime(object):
    """The datetime service definition.
    """

    @staticmethod
    def GetTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datetime.DateTime/GetTime',
            interfaces_dot_datetime__pb2.TimeRequest.SerializeToString,
            interfaces_dot_datetime__pb2.TimeReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datetime.DateTime/GetDate',
            interfaces_dot_datetime__pb2.DateRequest.SerializeToString,
            interfaces_dot_datetime__pb2.DateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
