# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interfaces/pet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='interfaces/pet.proto',
  package='pet',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14interfaces/pet.proto\x12\x03pet\"Z\n\nPetRequest\x12\"\n\x04size\x18\x01 \x01(\x0e\x32\x14.pet.PetRequest.Size\"(\n\x04Size\x12\t\n\x05SMALL\x10\x00\x12\n\n\x06MEDIUM\x10\x01\x12\t\n\x05LARGE\x10\x02\",\n\x0bPetResponse\x12\x0f\n\x07petType\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\"\n\x0fPetSoundRequest\x12\x0f\n\x07petType\x18\x01 \x01(\t\"!\n\x10PetSoundResponse\x12\r\n\x05sound\x18\x01 \x01(\t27\n\x06GetPet\x12-\n\x06GetPet\x12\x0f.pet.PetRequest\x1a\x10.pet.PetResponse\"\x00\x32K\n\x0bGetPetSound\x12<\n\x0bGetPetSound\x12\x14.pet.PetSoundRequest\x1a\x15.pet.PetSoundResponse\"\x00\x62\x06proto3'
)



_PETREQUEST_SIZE = _descriptor.EnumDescriptor(
  name='Size',
  full_name='pet.PetRequest.Size',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SMALL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MEDIUM', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LARGE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=79,
  serialized_end=119,
)
_sym_db.RegisterEnumDescriptor(_PETREQUEST_SIZE)


_PETREQUEST = _descriptor.Descriptor(
  name='PetRequest',
  full_name='pet.PetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='pet.PetRequest.size', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PETREQUEST_SIZE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=119,
)


_PETRESPONSE = _descriptor.Descriptor(
  name='PetResponse',
  full_name='pet.PetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='petType', full_name='pet.PetResponse.petType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='pet.PetResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=165,
)


_PETSOUNDREQUEST = _descriptor.Descriptor(
  name='PetSoundRequest',
  full_name='pet.PetSoundRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='petType', full_name='pet.PetSoundRequest.petType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=201,
)


_PETSOUNDRESPONSE = _descriptor.Descriptor(
  name='PetSoundResponse',
  full_name='pet.PetSoundResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sound', full_name='pet.PetSoundResponse.sound', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=236,
)

_PETREQUEST.fields_by_name['size'].enum_type = _PETREQUEST_SIZE
_PETREQUEST_SIZE.containing_type = _PETREQUEST
DESCRIPTOR.message_types_by_name['PetRequest'] = _PETREQUEST
DESCRIPTOR.message_types_by_name['PetResponse'] = _PETRESPONSE
DESCRIPTOR.message_types_by_name['PetSoundRequest'] = _PETSOUNDREQUEST
DESCRIPTOR.message_types_by_name['PetSoundResponse'] = _PETSOUNDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PetRequest = _reflection.GeneratedProtocolMessageType('PetRequest', (_message.Message,), {
  'DESCRIPTOR' : _PETREQUEST,
  '__module__' : 'interfaces.pet_pb2'
  # @@protoc_insertion_point(class_scope:pet.PetRequest)
  })
_sym_db.RegisterMessage(PetRequest)

PetResponse = _reflection.GeneratedProtocolMessageType('PetResponse', (_message.Message,), {
  'DESCRIPTOR' : _PETRESPONSE,
  '__module__' : 'interfaces.pet_pb2'
  # @@protoc_insertion_point(class_scope:pet.PetResponse)
  })
_sym_db.RegisterMessage(PetResponse)

PetSoundRequest = _reflection.GeneratedProtocolMessageType('PetSoundRequest', (_message.Message,), {
  'DESCRIPTOR' : _PETSOUNDREQUEST,
  '__module__' : 'interfaces.pet_pb2'
  # @@protoc_insertion_point(class_scope:pet.PetSoundRequest)
  })
_sym_db.RegisterMessage(PetSoundRequest)

PetSoundResponse = _reflection.GeneratedProtocolMessageType('PetSoundResponse', (_message.Message,), {
  'DESCRIPTOR' : _PETSOUNDRESPONSE,
  '__module__' : 'interfaces.pet_pb2'
  # @@protoc_insertion_point(class_scope:pet.PetSoundResponse)
  })
_sym_db.RegisterMessage(PetSoundResponse)



_GETPET = _descriptor.ServiceDescriptor(
  name='GetPet',
  full_name='pet.GetPet',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=238,
  serialized_end=293,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPet',
    full_name='pet.GetPet.GetPet',
    index=0,
    containing_service=None,
    input_type=_PETREQUEST,
    output_type=_PETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETPET)

DESCRIPTOR.services_by_name['GetPet'] = _GETPET


_GETPETSOUND = _descriptor.ServiceDescriptor(
  name='GetPetSound',
  full_name='pet.GetPetSound',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=295,
  serialized_end=370,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPetSound',
    full_name='pet.GetPetSound.GetPetSound',
    index=0,
    containing_service=None,
    input_type=_PETSOUNDREQUEST,
    output_type=_PETSOUNDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETPETSOUND)

DESCRIPTOR.services_by_name['GetPetSound'] = _GETPETSOUND

# @@protoc_insertion_point(module_scope)
