# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datetime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='datetime.proto',
  package='datetime',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x64\x61tetime.proto\x12\x08\x64\x61tetime\"\x19\n\tTimeReply\x12\x0c\n\x04time\x18\x01 \x01(\t\"\x19\n\tDateReply\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"\x07\n\x05\x45mpty26\n\x04Time\x12.\n\x04Time\x12\x0f.datetime.Empty\x1a\x13.datetime.TimeReply\"\x00\x32\x36\n\x04\x44\x61te\x12.\n\x04\x44\x61te\x12\x0f.datetime.Empty\x1a\x13.datetime.DateReply\"\x00\x62\x06proto3'
)




_TIMEREPLY = _descriptor.Descriptor(
  name='TimeReply',
  full_name='datetime.TimeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='datetime.TimeReply.time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=53,
)


_DATEREPLY = _descriptor.Descriptor(
  name='DateReply',
  full_name='datetime.DateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='datetime.DateReply.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=80,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='datetime.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['TimeReply'] = _TIMEREPLY
DESCRIPTOR.message_types_by_name['DateReply'] = _DATEREPLY
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeReply = _reflection.GeneratedProtocolMessageType('TimeReply', (_message.Message,), {
  'DESCRIPTOR' : _TIMEREPLY,
  '__module__' : 'datetime_pb2'
  # @@protoc_insertion_point(class_scope:datetime.TimeReply)
  })
_sym_db.RegisterMessage(TimeReply)

DateReply = _reflection.GeneratedProtocolMessageType('DateReply', (_message.Message,), {
  'DESCRIPTOR' : _DATEREPLY,
  '__module__' : 'datetime_pb2'
  # @@protoc_insertion_point(class_scope:datetime.DateReply)
  })
_sym_db.RegisterMessage(DateReply)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'datetime_pb2'
  # @@protoc_insertion_point(class_scope:datetime.Empty)
  })
_sym_db.RegisterMessage(Empty)



_TIME = _descriptor.ServiceDescriptor(
  name='Time',
  full_name='datetime.Time',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=91,
  serialized_end=145,
  methods=[
  _descriptor.MethodDescriptor(
    name='Time',
    full_name='datetime.Time.Time',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_TIMEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TIME)

DESCRIPTOR.services_by_name['Time'] = _TIME


_DATE = _descriptor.ServiceDescriptor(
  name='Date',
  full_name='datetime.Date',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=147,
  serialized_end=201,
  methods=[
  _descriptor.MethodDescriptor(
    name='Date',
    full_name='datetime.Date.Date',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_DATEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATE)

DESCRIPTOR.services_by_name['Date'] = _DATE

# @@protoc_insertion_point(module_scope)
