# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import datetime_pb2 as datetime__pb2


class TimeStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Time = channel.unary_unary(
                '/datetime.Time/Time',
                request_serializer=datetime__pb2.Empty.SerializeToString,
                response_deserializer=datetime__pb2.TimeReply.FromString,
                )


class TimeServicer(object):
    """The greeting service definition.
    """

    def Time(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Time': grpc.unary_unary_rpc_method_handler(
                    servicer.Time,
                    request_deserializer=datetime__pb2.Empty.FromString,
                    response_serializer=datetime__pb2.TimeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datetime.Time', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Time(object):
    """The greeting service definition.
    """

    @staticmethod
    def Time(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datetime.Time/Time',
            datetime__pb2.Empty.SerializeToString,
            datetime__pb2.TimeReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class DateStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Date = channel.unary_unary(
                '/datetime.Date/Date',
                request_serializer=datetime__pb2.Empty.SerializeToString,
                response_deserializer=datetime__pb2.DateReply.FromString,
                )


class DateServicer(object):
    """The greeting service definition.
    """

    def Date(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Date': grpc.unary_unary_rpc_method_handler(
                    servicer.Date,
                    request_deserializer=datetime__pb2.Empty.FromString,
                    response_serializer=datetime__pb2.DateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datetime.Date', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Date(object):
    """The greeting service definition.
    """

    @staticmethod
    def Date(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/datetime.Date/Date',
            datetime__pb2.Empty.SerializeToString,
            datetime__pb2.DateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
